name: Generate Lilypond music sheets
on:
  push:
    branches:
      - master
jobs:
  build_sheets:
    runs-on: ubuntu-latest
    env:
        LILYPOND_FILES: "*.ly"
    steps:
      - name: Checkout Source 
        uses: actions/checkout@v1
      - name: Get changed files
        id: getfile
        run: |
          echo "::set-output name=files::$(find ${{github.workspace}} -iname "${{ env.LILYPOND_FILES }}" -printf '"%P"\0' | xargs -r0)"
      - name: LILYPOND files considered echo output
        run: |
          echo ${{ steps.getfile.outputs.files }}
      - name: Generate PDF music sheets
        uses: alexandre-touret/lilypond-github-action@master
        with:
            args: -V -fpdf -fpng -fmidi ${{ steps.getfile.outputs.files }}
      - name: Push Local Changes
        run: |
          git config --local user.email "a.n.vinogradov@gmail.com"
          git config --local user.name "Alexey N. Vinogradov"
          mkdir -p ${{github.workspace}}/docs/
          mv -f *.midi ${{github.workspace}}/docs/
          mv -f *.pdf ${{github.workspace}}/docs/
          mv -f *.png ${{github.workspace}}/docs/
          git add ${{github.workspace}}/docs/
          git commit -m "Add changes" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: master
          github_token: ${{ secrets.GITHUB_TOKEN }}
